#!/usr/bin/env bash
# Supabase Fix Implementation Checklist
# Use this to track your progress through the implementation

echo "🚀 LinguaFabric - Supabase Language Creation Fix"
echo "=================================================="
echo ""
echo "This script provides a checklist for implementing the fix."
echo "Follow each step carefully and mark completion."
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}PHASE 1: PREPARATION${NC}"
echo "======================"
echo ""
echo "[ ] Have you read docs/SUMMARY.md?"
echo "    → Quick overview of the problem and solution"
echo ""
echo "[ ] Do you have access to Supabase Dashboard?"
echo "    → Go to https://app.supabase.com"
echo ""
echo "[ ] Is your project running locally?"
echo "    → npm run dev should be running"
echo ""

echo -e "${YELLOW}PHASE 2: APPLY SQL FIX #1 (User Creation Trigger)${NC}"
echo "====================================================="
echo ""
echo "Step 1: Open Supabase Dashboard"
echo "  [ ] Navigate to: SQL Editor"
echo ""
echo "Step 2: Run Trigger SQL"
echo "  [ ] Click: New Query"
echo "  [ ] Open file: docs/SUPABASE_FIXES.sql"
echo "  [ ] Copy entire file content"
echo "  [ ] Paste into SQL Editor"
echo "  [ ] Click: Run"
echo ""
echo "Step 3: Verify Success"
echo "  [ ] No errors in output"
echo "  [ ] See: 'CREATE FUNCTION created successfully'"
echo "  [ ] See: 'CREATE TRIGGER created successfully'"
echo ""

echo -e "${YELLOW}PHASE 3: APPLY SQL FIX #2 (RLS Policies)${NC}"
echo "========================================="
echo ""
echo "Step 1: Open Supabase Dashboard"
echo "  [ ] Still in SQL Editor"
echo ""
echo "Step 2: Run RLS Policies SQL"
echo "  [ ] Click: New Query"
echo "  [ ] Open file: docs/SUPABASE_RLS_IMPROVEMENTS.sql"
echo "  [ ] Copy entire file content"
echo "  [ ] Paste into SQL Editor"
echo "  [ ] Click: Run"
echo ""
echo "Step 3: Verify Success"
echo "  [ ] No errors in output (DROP warnings are OK)"
echo "  [ ] See: 'CREATE POLICY created successfully' (4 times)"
echo ""

echo -e "${YELLOW}PHASE 4: VERIFY IMPLEMENTATION${NC}"
echo "================================="
echo ""
echo "Run these verification queries in Supabase SQL Editor:"
echo ""
echo "Query 1: Check Trigger Function"
echo "  [ ] Copy this query:"
echo "      SELECT proname FROM pg_proc WHERE proname = 'handle_new_user';"
echo "  [ ] Expected result: 1 row with 'handle_new_user'"
echo ""
echo "Query 2: Check RLS Policies"
echo "  [ ] Copy this query:"
echo "      SELECT policyname FROM pg_policies WHERE tablename = 'language_collaborators' ORDER BY policyname;"
echo "  [ ] Expected result: 4 rows (delete, insert, select, update)"
echo ""
echo "Query 3: Check Users Table Structure"
echo "  [ ] Copy this query:"
echo "      SELECT column_name FROM information_schema.columns WHERE table_name = 'users' ORDER BY column_name;"
echo "  [ ] Expected columns: auth_id, created_at, default_language_depth, display_name, email, id, profile_image_url, theme, activity_permissions, updated_at"
echo ""

echo -e "${YELLOW}PHASE 5: TEST IN APPLICATION${NC}"
echo "=============================="
echo ""
echo "Test 1: Sign Up New User"
echo "  [ ] Go to: http://localhost:5173"
echo "  [ ] Navigate to: Sign Up page"
echo "  [ ] Fill form:"
echo "      Email: test-$(date +%s)@example.com (use unique email)"
echo "      Password: TestPassword123"
echo "  [ ] Click: Sign Up"
echo "  [ ] Check: No errors in browser console"
echo ""
echo "Test 2: Verify User in Database"
echo "  [ ] Supabase Dashboard → Table Editor"
echo "  [ ] Click: users table"
echo "  [ ] Look for: Your new user with the email you just signed up with"
echo "  [ ] Check: auth_id, email, display_name fields are populated"
echo ""
echo "Test 3: Create a Language"
echo "  [ ] In app, navigate to: Create New Language"
echo "  [ ] Fill form:"
echo "      Name: Test Language $(date +%s)"
echo "      Description: A test language to verify the fix"
echo "      Icon: 🧪 (or leave default)"
echo "  [ ] Click: Create Language"
echo "  [ ] Check: No errors in browser console"
echo "  [ ] Look for: ✅ checkmarks in console logs"
echo ""
echo "Test 4: Verify Language in Database"
echo "  [ ] Supabase Dashboard → Table Editor"
echo "  [ ] Click: languages table"
echo "  [ ] Look for: Your new language with matching name"
echo "  [ ] Check: owner_id matches your user's ID"
echo ""
echo "Test 5: Verify Collaborator Entry"
echo "  [ ] Supabase Dashboard → Table Editor"
echo "  [ ] Click: language_collaborators table"
echo "  [ ] Look for: New entry with:"
echo "      language_id = your language's ID"
echo "      user_id = your user's ID"
echo "      role = 'owner'"
echo ""

echo -e "${YELLOW}PHASE 6: SUCCESS CRITERIA${NC}"
echo "=========================="
echo ""
echo "All of these must pass:"
echo ""
echo "Database Checks:"
echo "  [ ] Trigger function exists in pg_proc"
echo "  [ ] 4 RLS policies exist for language_collaborators"
echo "  [ ] users table has auth_id column"
echo "  [ ] languages table has owner_id column"
echo ""
echo "Application Checks:"
echo "  [ ] New user appears in users table after signup"
echo "  [ ] No errors in browser console during signup"
echo "  [ ] Language creation completes without errors"
echo "  [ ] Console shows ✅ checkmarks at each step"
echo ""
echo "Database Consistency:"
echo "  [ ] Every language has an owner_id"
echo "  [ ] Every language has at least one collaborator (owner)"
echo "  [ ] Every collaborator entry has role='owner' for creators"
echo "  [ ] User IDs in language_collaborators match entries in users table"
echo ""

echo -e "${YELLOW}PHASE 7: TROUBLESHOOTING${NC}"
echo "=========================="
echo ""
echo "If something fails, check:"
echo ""
echo "Issue: 'Collaborator insert failed'"
echo "  [ ] Run: SELECT * FROM users WHERE email = 'your-email';"
echo "  [ ] Result should show your user"
echo "  [ ] If not, trigger didn't fire - sign up a new user"
echo ""
echo "Issue: 'RLS policy error'"
echo "  [ ] Verify policies exist with Query 2"
echo "  [ ] Re-run docs/SUPABASE_RLS_IMPROVEMENTS.sql"
echo ""
echo "Issue: 'Language won't create'"
echo "  [ ] Check browser console for specific error"
echo "  [ ] Verify name is unique per user"
echo "  [ ] Verify all required fields filled"
echo ""

echo -e "${YELLOW}PHASE 8: DOCUMENTATION${NC}"
echo "======================="
echo ""
echo "Reference docs created:"
echo "  [ ] docs/README_SUPABASE_FIX.md - Start here"
echo "  [ ] docs/SUMMARY.md - Visual overview"
echo "  [ ] docs/QUICK_REFERENCE.md - 5-minute guide"
echo "  [ ] docs/IMPLEMENTATION_GUIDE.md - Complete guide"
echo "  [ ] docs/SUPABASE_FIXES.sql - Trigger SQL"
echo "  [ ] docs/SUPABASE_RLS_IMPROVEMENTS.sql - Policies SQL"
echo ""
echo "See these for detailed help:"
echo "  → docs/IMPLEMENTATION_GUIDE.md#troubleshooting"
echo "  → docs/QUICK_REFERENCE.md"
echo ""

echo -e "${GREEN}🎉 IMPLEMENTATION COMPLETE!${NC}"
echo "============================="
echo ""
echo "Next steps:"
echo "  1. Mark all checkboxes above"
echo "  2. If all pass: You're done! ✅"
echo "  3. If any fail: Check troubleshooting section"
echo "  4. Document any issues found"
echo ""
echo "For detailed info:"
echo "  → Read: docs/IMPLEMENTATION_GUIDE.md"
echo "  → Quick help: docs/QUICK_REFERENCE.md"
echo "  → Visual summary: docs/SUMMARY.md"
echo ""
